version: '3'

services:
  notebook:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=<you-openai-api-key>
      - AI21_API_KEY=<you-ai21-api-key>
      - ANTHROPIC_API_KEY=<you-anthropic-api-key>
      - COHERE_API_KEY=<you-cohere-api-key>
      - HUGGINGFACEHUB_API_TOKEN=<you-huggingfacehub-api-token>